'''
this file contains all relevant game constants
'''

# probabilities heavily depend on frame rate

from colorama import Fore, Back, Style

BUFFER_RIGHT = 10
BUFFER_DOWN = 10

MIN_HEIGHT = 20
MIN_WIDTH = 60

BG_COLOR = Back.BLACK
BG_ACCENT_COLOR = Back.BLUE
ACCENT_AMT = 0.01
GND_COLOR = Back.MAGENTA
SKY_COLOR = Back.MAGENTA

BAR_HEIGHT = 2
BAR_DEFAULT_COLOR = Back.GREEN

ART_BASE_PATH = 'art'
ART_YODA_PATH = 'yoda.py'

GND_HEIGHT = 3
SKY_DEPTH = 3

GRAVITY_Y = 0
GRAVITY_X = 0.26
DRAG_COEFF = 0.04

GAME_SPEED = 1.5
KEY_FORCE = 2.5

MANDALORIAN_START_Y = 40

MAX_LIVES = 3

SHIELD_UP_TIME = 5
SHIELD_SLEEP_TIME = 20

BOOST_SPEED = 3
BOOST_UP_TIME = 5
BOOST_PROBAB = 0.1

MAGNET_FORCE = 1.5
MAGNET_PROBAB = 0.003

MIN_BEAM_DIST_X = 25  # unit: Frames
MIN_BEAM_SIZE = 6
MAX_BEAM_SIZE = 10

MIN_COIN_SIZE = 3
MAX_COIN_SIZE = 5
COIN_PROBAB = 0.08

MANDALORIAN_BULLET_SPEED = 3

BOSS_ARRIVAL_TIME = 20
BOSS_MAX_STRENGTH = 20
BOSS_BULLET_SPEED = 4
BOSS_SHOOT_PROBAB = 0.1
BOSS_TIME_LIMIT = 50
BOSS_BAR_WIDTH = 10

SCORE_TIME_FACTOR = 1
SCORE_COIN_FACTOR = 4
SCORE_BEAM_FACTOR = 6
SCORE_BOOST_FACTOR = 10
SCORE_BOSS_HIT_FACTOR = 6
SCORE_BOSS_BULLET_FACTOR = 6

DRAGON_TIME = 5